export const LOADING = "LOADING";

export const FAILED = "FAILED";

export const PLANTADDEDSUCCESSFULLY = "PLANTADDEDSUCCESSFULLY";

export const GETALLPLANTS = "GETALLPLANTS";

export const DELETEPLANT = "DELETEPLANT";
