export const PLANTLOADING = "PLANTLOADING";

export const PLANTFAILED = "PLANTFAILED";

export const PLANTADDEDSUCCESSFULLY = "PLANTADDEDSUCCESSFULLY";

export const GETALLPLANTS = "GETALLPLANTS";

export const EDITPLANT = "EDITPLANT";

export const DELETEPLANT = "DELETEPLANT";
